"""Render the batter shot analysis as a PDF report plus a JSON artifact.

Mirrors ``render/report.py`` (reportlab Platypus, no system deps): provenance
header, the sampled-frames contact sheet, a per-dimension ratings table, and the
coaching write-up.
"""

from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from ..models.batter_schemas import BatterReportData


def _esc(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build_batter_report(data: BatterReportData, out_dir: str | Path) -> str:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # JSON artifact (full structured analysis).
    (out_dir / "analysis.json").write_text(data.model_dump_json(indent=2))

    pdf_path = str(out_dir / "report.pdf")
    doc = SimpleDocTemplate(pdf_path, pagesize=A4,
                            leftMargin=1.5 * cm, rightMargin=1.5 * cm,
                            topMargin=1.5 * cm, bottomMargin=1.5 * cm)
    styles = getSampleStyleSheet()
    story = []

    a = data.analysis
    v = data.video
    story.append(Paragraph("Batter Shot Analysis", styles["Title"]))
    story.append(Paragraph(f"Run: {_esc(data.run_id)}", styles["Normal"]))
    story.append(Spacer(1, 0.3 * cm))

    header_rows = [
        ["Clip", Path(data.clip_path).name],
        ["Resolution", f"{v.width} x {v.height}"],
        ["fps", f"{v.fps:g}"],
        ["Model / backend", f"{data.model}  ({data.backend})"],
        ["Shot", f"{a.shot_type}  [{a.shot_family}]"],
        ["Confidence", f"{a.confidence:.0%}"],
        ["Overall", a.overall_rating],
    ]
    if data.contact_detected:
        header_rows.append(
            ["Bat-ball contact (audio)", f"~{data.contact_time_s:.2f}s into clip"])
    t = Table(header_rows, colWidths=[5 * cm, 11 * cm])
    t.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("BACKGROUND", (0, 0), (0, -1), colors.whitesmoke),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.4 * cm))

    # Sampled-frames contact sheet.
    if data.contact_sheet_png and Path(data.contact_sheet_png).exists():
        story.append(Paragraph("Sampled frames (backlift &rarr; follow-through)",
                               styles["Heading2"]))
        iw, ih = ImageReader(data.contact_sheet_png).getSize()
        w = 17 * cm
        story.append(Image(data.contact_sheet_png, width=w, height=w * ih / iw))
        story.append(Spacer(1, 0.3 * cm))

    # Per-dimension technique table.
    story.append(Paragraph("Technique assessment", styles["Heading2"]))
    cell = styles["BodyText"]
    rows = [["Dimension", "Rating", "Observation"]]
    for d in a.dimensions:
        rows.append([Paragraph(_esc(d.name), cell),
                     Paragraph(_esc(d.rating), cell),
                     Paragraph(_esc(d.observation), cell)])
    dt = Table(rows, colWidths=[3.5 * cm, 2.5 * cm, 10 * cm])
    dt.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.whitesmoke]),
    ]))
    story.append(dt)
    story.append(Spacer(1, 0.4 * cm))

    if a.strengths:
        story.append(Paragraph("Strengths", styles["Heading2"]))
        for s in a.strengths:
            story.append(Paragraph(f"&bull; {_esc(s)}", styles["Normal"]))
        story.append(Spacer(1, 0.2 * cm))
    if a.faults:
        story.append(Paragraph("Areas to improve", styles["Heading2"]))
        for f in a.faults:
            story.append(Paragraph(f"&bull; {_esc(f)}", styles["Normal"]))
        story.append(Spacer(1, 0.2 * cm))

    story.append(Paragraph("Coaching summary", styles["Heading2"]))
    story.append(Paragraph(_esc(a.coaching_summary), styles["Normal"]))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        f"<i>Generated by {_esc(data.model)} ({_esc(data.backend)}) from "
        f"{len(data.frame_times_s)} sampled frames. This is an automated "
        "vision-model assessment, not a substitute for a qualified coach.</i>",
        styles["Normal"]))

    doc.build(story)
    return pdf_path
